### ISSUE TITLE
CrazyRadio PA 2

### ISSUE THREAD

**Issue by Yasha-ops** [RFStorm/mousejack#54]
Does not seem to be compatible with the CrazyRadio PA 2

**Comment by throwawaya609** [comment]
That's the one I have, are you sure?

**Comment by EvWoDev** [comment]
@Yasha-ops having the same issue you found a solution?

**Comment by seabird34** [comment]
@Yasha-ops @JohnDoeEh @BastilleResearch any update?

**Comment by xaxaxa7b9** [comment]
is this working with crazyradio 2.0? @Yasha-ops @JohnDoeEh @seabird34 @BastilleResearch @throwawaya609 @marcnewlin

**Comment by throwawaya609** [comment]
> is this working with crazyradio 2.0? @Yasha-ops @JohnDoeEh @seabird34 @BastilleResearch @throwawaya609 @marcnewlin

Works like a charm for me

I got it fixed with this: https://github.com/BastilleResearch/mousejack/issues/55

**Comment by EvWoDev** [comment]
@Yasha-ops @throwawaya609 @seabird34 @xaxaxa7b9.

I found the issue. This is build for a nrf24l01 chip. The crazyradio 2.0 is based on the nRF52840 chip.
This wil not work because its build for nrf24l01. Try and search mousejacking for nRF52840.

**Comment by seeklakhan** [comment]
@Yasha-ops  @EvilWolv @throwawaya609  @seabird34  @xaxaxa7b9 
Any one found the solution for Crazy Radio 2.0 ?

**Comment by cuhsat** [comment]
Asking in late 2025, if someone was able to get this working with CrazyRadio 2.0?

**Comment by Yasha-ops** [comment]
Still the same problem @EvWoDev can you please give a link ?? 
 @xaxaxa7b9 @seabird34  @throwawaya609 Nothing on your sides ?
